package br.umc.audit;

public enum AuditAction {

    LOGIN,
    LOGOUT,
    CADASTRO_USUARIO,
    ESQUECI_SENHA,
    REDEFINIR_SENHA,
    ALTERAR_SENHA,
    DESATIVAR_USUARIO,
    ATUALIZAR_PERFIL_USUARIO,
    LISTAR_USUARIOS,
    CONSULTAR_USUARIO,

    CADASTRAR_PESSOA,
    ATUALIZAR_PESSOA,
    EXCLUIR_PESSOA,
    LISTAR_PESSOAS,
    CONSULTAR_PESSOA,
    BUSCAR_PESSOAS,

    CADASTRAR_ENDERECO,
    ATUALIZAR_ENDERECO,
    EXCLUIR_ENDERECO,
    LISTAR_ENDERECOS,
    CONSULTAR_ENDERECO,
    VINCULAR_ENDERECO,
    DESVINCULAR_ENDERECO,

    ACESSO_NEGADO,
    ERRO_INTERNO,
    CONSULTA_AUDITORIA
}
